# Generated by Django 5.0.14 on 2026-04-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.CharField(max_length=255)),
                ('client_type', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('detail_heading', models.CharField(max_length=200)),
                ('detail_intro', models.TextField()),
                ('detail_body', models.TextField()),
                ('detail_body_two', models.TextField()),
                ('gallery_image_left', models.CharField(blank=True, max_length=255)),
                ('gallery_image_right', models.CharField(blank=True, max_length=255)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon_class', models.CharField(default='flaticon-design-thinking', max_length=100)),
                ('short_description', models.TextField()),
                ('detail_heading', models.CharField(max_length=200)),
                ('detail_intro', models.TextField()),
                ('detail_body', models.TextField()),
                ('detail_body_two', models.TextField()),
                ('detail_image', models.CharField(blank=True, max_length=255)),
                ('gallery_image_left', models.CharField(blank=True, max_length=255)),
                ('gallery_image_right', models.CharField(blank=True, max_length=255)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('faq_one_question', models.CharField(blank=True, max_length=255)),
                ('faq_one_answer', models.TextField(blank=True)),
                ('faq_two_question', models.CharField(blank=True, max_length=255)),
                ('faq_two_answer', models.TextField(blank=True)),
                ('faq_three_question', models.CharField(blank=True, max_length=255)),
                ('faq_three_answer', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
