from django.db import migrations


def seed_content(apps, schema_editor):
    Service = apps.get_model('main', 'Service')
    Project = apps.get_model('main', 'Project')

    services = [
        {
            'title': 'Quantity Surveying',
            'slug': 'quantity-surveying',
            'icon_class': 'flaticon-it-department',
            'short_description': 'Cost planning, bills of quantities, tender documents and financial control from concept to final account.',
            'detail_heading': 'Quantity Surveying and Project Cost Control',
            'detail_intro': 'Our quantity surveying consultancy supports developers, institutions, contractors and financiers from concept to final account. We prepare preliminary cost estimates, bills of approximate quantities, bills of quantities, tender documents, tender analysis reports, construction contracts, cashflow projections, interim valuations, variation accounts and final accounts.',
            'detail_body': 'Shelta Cost Solutions helps clients make informed commercial decisions while safeguarding time, cost and quality outcomes. We advise on procurement strategy, tender evaluation, budget monitoring, change management and account settlement so projects stay financially disciplined throughout delivery.',
            'detail_body_two': 'Our work spans luxury apartments, affordable housing, bank fit-outs, commercial offices, warehouses, retail markets, schools, social buildings, hotels, hostels and sports facilities. This broad exposure gives our team practical, locally informed advice on procurement, budgeting, contract performance and project controls.',
            'detail_image': 'assets/img/service/services-1.html',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-8.jpg',
            'checklist': [
                'Preparation of cost estimates, BOQs and tender documents',
                'Tender analysis, contract documentation and payment certification',
                'Variation appraisal, cost reporting and final account preparation',
                'Commercial support from feasibility to project close-out',
            ],
            'faq_one_question': 'What does your quantity surveying service include?',
            'faq_one_answer': 'It covers cost estimates, bills of quantities, tender documentation, tender analysis, contract preparation, interim valuations, variation appraisals and final account preparation.',
            'faq_two_question': 'Do you support both private and public sector clients?',
            'faq_two_answer': 'Yes. We support developers, institutions, financiers, contractors and public-sector clients across multiple project types.',
            'faq_three_question': 'Which sectors have you served?',
            'faq_three_answer': 'Our assignments include apartments, offices, retail outlets, warehouses, schools, hotels, hostels and sports projects including Bukhungu Stadium Phase 2.',
            'sort_order': 1,
            'featured': True,
        },
        {
            'title': 'Contract Administration',
            'slug': 'contract-administration',
            'icon_class': 'flaticon-project',
            'short_description': 'Structured administration of contracts, certifications, variations and obligations across the life of the project.',
            'detail_heading': 'Contract Administration and Commercial Control',
            'detail_intro': 'We administer construction contracts with a focus on accountability, documentation and commercial clarity. Our team manages valuations, change control, payment recommendations, contractor communications and contract compliance so obligations remain clear to all parties.',
            'detail_body': 'Contract administration is one of the main ways clients protect budgets and reduce disputes. We maintain a dependable record of instructions, valuations, progress and contractual events, helping project teams respond early to emerging issues instead of reacting after claims escalate.',
            'detail_body_two': 'This capability supports developers, institutions and contractors who need accurate payment certification, measured change control and disciplined close-out. It is especially valuable on fast-moving residential, commercial and public infrastructure assignments.',
            'detail_image': 'assets/img/service/services-1.html',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-4.jpg',
            'checklist': [
                'Interim valuations and payment certification',
                'Variation control and supporting commercial records',
                'Contract correspondence and obligation tracking',
                'Final account review and close-out support',
            ],
            'faq_one_question': 'Why is contract administration important?',
            'faq_one_answer': 'It keeps the project commercially organised and helps clients make timely, defensible decisions on payments, change and obligations.',
            'faq_two_question': 'Can you support live projects with existing contracts?',
            'faq_two_answer': 'Yes. We can join ongoing projects to review records, improve controls and support valuation, change management and account settlement.',
            'faq_three_question': 'Does this help reduce disputes?',
            'faq_three_answer': 'Yes. Good records, disciplined instructions and consistent valuation reduce ambiguity and lower the risk of disputes later in the project.',
            'sort_order': 2,
            'featured': True,
        },
        {
            'title': 'Project Management',
            'slug': 'project-management',
            'icon_class': 'flaticon-design-thinking',
            'short_description': 'Coordination of scope, budget, procurement, programme and reporting to keep delivery aligned with client goals.',
            'detail_heading': 'Project Management for Timely Delivery',
            'detail_intro': 'Shelta Cost coordinates teams, consultants and delivery priorities to maintain control across time, cost and quality. Our project management approach is built around clear communication, accountable programming and reliable reporting for client decision-making.',
            'detail_body': 'We support the full project lifecycle from inception and procurement planning through construction monitoring and close-out. The goal is to give clients an informed overview of delivery performance while helping consultants and contractors work against an agreed programme and commercial framework.',
            'detail_body_two': 'This service is suited to private developments, institutional projects and infrastructure works where multiple stakeholders need strong coordination. It complements our quantity surveying and contract administration capability, giving clients both strategic and commercial oversight.',
            'detail_image': 'assets/img/service/services-1.html',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-6.jpg',
            'checklist': [
                'Programme planning, reporting and coordination',
                'Procurement sequencing and consultant management',
                'Risk review, issue tracking and decision support',
                'Delivery oversight across time, cost and quality',
            ],
            'faq_one_question': 'What does project management cover?',
            'faq_one_answer': 'It covers planning, coordination, monitoring, reporting and stakeholder management to keep the project aligned with approved objectives.',
            'faq_two_question': 'Do you work alongside client teams?',
            'faq_two_answer': 'Yes. We can act as an external project management partner or support an existing in-house team with structured oversight and reporting.',
            'faq_three_question': 'Which projects benefit most from this service?',
            'faq_three_answer': 'Projects with multiple consultants, contractors, approvals and reporting demands benefit most from formal project management.',
            'sort_order': 3,
            'featured': True,
        },
        {
            'title': 'Construction Management',
            'slug': 'construction-management',
            'icon_class': 'flaticon-data',
            'short_description': 'Site-focused coordination, buildability review and progress monitoring to improve delivery performance.',
            'detail_heading': 'Construction Management and Site Delivery Oversight',
            'detail_intro': 'Our construction management support strengthens the link between planning, contract controls and site execution. We help clients monitor progress, resolve coordination issues and improve reporting on live projects so delivery remains visible and accountable.',
            'detail_body': 'This service is useful where buildability, sequencing, supervision and contractor coordination directly affect time and cost outcomes. We focus on practical site issues, progress validation and action-oriented reporting rather than abstract planning alone.',
            'detail_body_two': 'By combining site-facing management with our commercial expertise, Shelta Cost helps clients understand how construction realities are affecting programme, cost movement and procurement. That improves decisions during the most active phases of delivery.',
            'detail_image': 'assets/img/service/services-1.html',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-2.jpg',
            'checklist': [
                'Progress monitoring and site coordination support',
                'Buildability review and delivery issue tracking',
                'Programme impact reporting and mitigation follow-up',
                'Integrated commercial and construction oversight',
            ],
            'faq_one_question': 'How is construction management different from project management?',
            'faq_one_answer': 'Construction management is more focused on live site execution, progress and coordination during the build stage.',
            'faq_two_question': 'Can this be used on contractor-led projects?',
            'faq_two_answer': 'Yes. It is especially useful where the client needs additional delivery visibility on contractor-led construction programmes.',
            'faq_three_question': 'Does this connect to cost monitoring?',
            'faq_three_answer': 'Yes. Site progress and buildability issues often affect cost and change, so we align construction oversight with our commercial reporting.',
            'sort_order': 4,
            'featured': False,
        },
        {
            'title': 'Feasibility Studies',
            'slug': 'feasibility-studies',
            'icon_class': 'flaticon-wrench-1',
            'short_description': 'Early-stage appraisal of viability, cost outlook, procurement options and delivery risk before major commitments are made.',
            'detail_heading': 'Feasibility Studies and Development Appraisal',
            'detail_intro': 'Before committing major capital, clients need dependable advice on viability, scope and delivery conditions. Our feasibility studies provide a structured early-stage review of project assumptions, cost outlook, programme implications and commercial options.',
            'detail_body': 'We help clients test ideas against real construction and market conditions so they can proceed with more confidence. This includes high-level budgeting, procurement thinking, risk identification and early decision support around scope, phasing and implementation strategy.',
            'detail_body_two': 'Feasibility advice is especially valuable for residential developments, institutional schemes and commercial projects where early choices have significant downstream cost effects. Our role is to bring practical cost intelligence into that early decision phase.',
            'detail_image': 'assets/img/service/services-1.html',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-3.jpg',
            'checklist': [
                'Preliminary development budgeting and option review',
                'Early procurement and phasing advice',
                'Risk identification and viability support',
                'Decision-ready reporting for project sponsors',
            ],
            'faq_one_question': 'What is included in a feasibility study?',
            'faq_one_answer': 'It typically includes early budgeting, risk review, viability considerations, delivery assumptions and advice on how to move into implementation.',
            'faq_two_question': 'Is this only for large developments?',
            'faq_two_answer': 'No. Smaller private and institutional projects also benefit from early commercial clarity before committing design and construction resources.',
            'faq_three_question': 'Can feasibility studies inform financing discussions?',
            'faq_three_answer': 'Yes. Clear early-stage cost and delivery information is often useful for lenders, investors and internal approvals.',
            'sort_order': 5,
            'featured': False,
        },
        {
            'title': 'Project Monitoring and Evaluation',
            'slug': 'project-monitoring-evaluation',
            'icon_class': 'flaticon-idea-1',
            'short_description': 'Progress verification, audit-style reporting and recommendations for lenders, developers and stakeholders.',
            'detail_heading': 'Monitoring, Evaluation and Independent Project Reporting',
            'detail_intro': 'Shelta Cost provides project monitoring and evaluation services for lenders, developers and other stakeholders who need an independent view of progress, cost movement and delivery performance. We review project status against approved scope, budget and programme expectations.',
            'detail_body': 'This service is especially useful where financing, governance or multi-party reporting requires clear evidence of progress and emerging risk. Our reports help decision-makers understand what is happening on site, how it compares to planned delivery and what actions may be needed next.',
            'detail_body_two': 'Our monitoring experience complements broader services such as claims awareness, contract administration and project management. Together, these give clients stronger visibility across both performance and commercial exposure on active projects.',
            'detail_image': 'assets/img/service/services-1.html',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-1.jpg',
            'checklist': [
                'Independent progress review and reporting',
                'Budget and programme tracking against approvals',
                'Recommendations for lenders and project sponsors',
                'Commercial visibility on risks, change and delivery status',
            ],
            'faq_one_question': 'Who uses monitoring and evaluation reports?',
            'faq_one_answer': 'Developers, lenders, institutions and investment stakeholders use them to understand progress, risk and budget movement.',
            'faq_two_question': 'Can this support funding drawdowns?',
            'faq_two_answer': 'Yes. Independent progress and cost reporting can support structured release decisions and ongoing financing oversight.',
            'faq_three_question': 'Does this connect to claims and dispute support?',
            'faq_three_answer': 'Yes. Strong project records and monitoring reports help identify issues early and provide context if claims or disputes emerge.',
            'sort_order': 6,
            'featured': True,
        },
    ]

    projects = [
        {
            'sector': 'Luxury Apartments',
            'title': 'DG West Serviced Apartments, Westlands',
            'slug': 'dg-west-serviced-apartments-westlands',
            'image': 'assets/img/portfolio/dgwest.jpeg',
            'client_type': 'Private Residential Development',
            'category': 'Luxury Apartments',
            'location': 'Westlands, Nairobi',
            'summary': 'A flagship luxury apartment assignment demonstrating Shelta Cost\'s capability on high-value residential developments.',
            'detail_heading': 'DG West Serviced Apartments, Westlands',
            'detail_intro': 'DG West Serviced Apartments is one of the landmark residential assignments in Shelta Cost Solutions Ltd\'s portfolio. It reflects the firm\'s role in supporting premium apartment development through reliable cost advice, commercial administration and disciplined project controls.',
            'detail_body': 'High-end residential projects place pressure on budget alignment, specification decisions and stakeholder reporting. Shelta Cost\'s value on developments like DG West lies in structuring the cost information, procurement support and commercial review needed to keep the project aligned with client expectations as design and delivery progress.',
            'detail_body_two': 'This assignment sits within a broader track record that includes Forest Gardens Apartments, Zanzi Court Apartments and other residential schemes. Across these projects, the firm has supported clients with the same focus on cost certainty, accountability and timely advice.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/dgwest.jpeg',
            'checklist': [
                'Cost planning and tender support for apartment delivery',
                'Commercial review across specification and budget decisions',
                'Contract administration and valuation support',
                'Project controls for high-value residential execution',
            ],
            'sort_order': 1,
            'featured': True,
        },
        {
            'sector': 'Apartment Developments',
            'title': 'Forest Gardens and Zanzi Court Apartments',
            'slug': 'forest-gardens-and-zanzi-court-apartments',
            'image': 'assets/img/portfolio/portfolio-4.jpg',
            'client_type': 'Private Residential Development',
            'category': 'Apartments',
            'location': 'Kenya',
            'summary': 'Residential developments spanning apartment planning, procurement and cost control support.',
            'detail_heading': 'Forest Gardens and Zanzi Court Apartments',
            'detail_intro': 'Forest Gardens and Zanzi Court Apartments represent Shelta Cost\'s wider residential experience beyond flagship luxury schemes. These assignments draw on the same quantity surveying and project support capabilities used across apartment developments of different scales and market positions.',
            'detail_body': 'Residential developments require tight control of scope, finishes, procurement decisions and cash flow expectations. Shelta Cost supports project teams by keeping cost and contract information usable, timely and decision-oriented throughout delivery.',
            'detail_body_two': 'The firm\'s residential portfolio demonstrates adaptability across premium apartments, mid-income schemes and other housing developments where clarity on cost and delivery risk is essential to project success.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-4.jpg',
            'checklist': [
                'Residential cost planning and procurement advice',
                'Tender documentation and commercial review',
                'Valuation, change control and account support',
                'Delivery visibility across apartment schemes',
            ],
            'sort_order': 2,
            'featured': False,
        },
        {
            'sector': 'Bank Fit-Outs',
            'title': 'Ecobank and GTBank Branch Networks',
            'slug': 'ecobank-and-gtbank-branch-networks',
            'image': 'assets/img/portfolio/portfolio-6.jpg',
            'client_type': 'Financial Institutions',
            'category': 'Branch Fit-Outs',
            'location': 'Kenya',
            'summary': 'Fit-out assignments for financial institutions requiring coordination, commercial control and repeatable delivery standards.',
            'detail_heading': 'Ecobank and GTBank Branch Networks',
            'detail_intro': 'Shelta Cost has supported financial-sector fit-out assignments including Ecobank and GTBank branch projects. These works demand speed, consistent delivery standards and strong control of commercial and contractual information across repeated fit-out programmes.',
            'detail_body': 'Branch fit-outs differ from one-off developments because they often involve rollout expectations, programme pressure and frequent coordination between client teams, designers and contractors. Shelta Cost brings discipline to valuation, contract administration, cost control and reporting across that environment.',
            'detail_body_two': 'This experience is reinforced by related fit-out assignments such as Stanbic BCC offices and other commercial interiors, giving the firm a strong base in fast-paced fit-out and refurbishment work.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-6.jpg',
            'checklist': [
                'Commercial control across multi-branch fit-out delivery',
                'Valuation, variation and reporting support',
                'Programme-sensitive coordination for fast-track works',
                'Consistent contract administration across repeated assignments',
            ],
            'sort_order': 3,
            'featured': True,
        },
        {
            'sector': 'Office Fit-Outs',
            'title': 'Stanbic BCC and Ruaka Square Offices',
            'slug': 'stanbic-bcc-and-ruaka-square-offices',
            'image': 'assets/img/portfolio/portfolio-2.jpg',
            'client_type': 'Commercial Occupiers and Developers',
            'category': 'Office Fit-Outs',
            'location': 'Kenya',
            'summary': 'Commercial office fit-out experience combining procurement, cost advice and delivery oversight.',
            'detail_heading': 'Stanbic BCC and Ruaka Square Offices',
            'detail_intro': 'Shelta Cost\'s office fit-out work includes assignments such as Stanbic BCC offices and Ruaka Square. These projects combine the demands of interior delivery, coordination and commercial control within occupied or high-performance commercial environments.',
            'detail_body': 'Office schemes benefit from close control of finishes, services coordination, programme sequencing and payment certification. The firm supports project teams with the contractual and commercial structure needed to keep these assignments moving without losing budget visibility.',
            'detail_body_two': 'This office fit-out capability complements the wider commercial and banking portfolio, giving clients a consultancy partner experienced in both building development and interior delivery environments.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-2.jpg',
            'checklist': [
                'Office fit-out budgeting and cost reporting',
                'Programme and coordination support',
                'Commercial administration and certification',
                'Change management for live commercial environments',
            ],
            'sort_order': 4,
            'featured': False,
        },
        {
            'sector': 'Commercial Developments',
            'title': 'Maisha Matt Shopping and Office Complex',
            'slug': 'maisha-matt-shopping-and-office-complex',
            'image': 'assets/img/portfolio/portfolio-8.jpg',
            'client_type': 'Commercial Development',
            'category': 'Mixed-Use Commercial',
            'location': 'Kenya',
            'summary': 'A mixed-use commercial assignment reflecting Shelta Cost\'s experience in retail and office development.',
            'detail_heading': 'Maisha Matt Shopping and Office Complex',
            'detail_intro': 'The Maisha Matt shopping and office complex reflects Shelta Cost\'s experience in mixed-use commercial development. Projects of this type require careful cost planning, coordinated procurement and close control of design and construction decisions that influence commercial viability.',
            'detail_body': 'Retail and office combinations introduce multiple user requirements, circulation needs and programme interfaces. Shelta Cost supports these developments by helping clients maintain commercial visibility while managing procurement, valuation and contract administration demands.',
            'detail_body_two': 'This project sits alongside other commercial assignments in the firm\'s portfolio and demonstrates experience beyond purely residential or institutional work. It reinforces the consultancy\'s ability to advise on diverse building typologies with different delivery pressures.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-8.jpg',
            'checklist': [
                'Commercial development cost planning and reporting',
                'Procurement support for mixed-use schemes',
                'Contract administration and payment review',
                'Delivery support across office and retail components',
            ],
            'sort_order': 5,
            'featured': True,
        },
        {
            'sector': 'Industrial Facilities',
            'title': 'Global Tea Factory and Warehouse Projects',
            'slug': 'global-tea-factory-and-warehouse-projects',
            'image': 'assets/img/portfolio/portfolio-6.jpg',
            'client_type': 'Industrial and Logistics Clients',
            'category': 'Factories and Warehouses',
            'location': 'Kenya',
            'summary': 'Industrial and warehouse assignments requiring practical cost control and delivery visibility.',
            'detail_heading': 'Global Tea Factory and Warehouse Projects',
            'detail_intro': 'Shelta Cost\'s industrial work includes Global Tea Factory and warehouse-related assignments. These projects bring a different set of priorities from apartments or fit-outs, with stronger emphasis on functionality, services, buildability and programme performance.',
            'detail_body': 'Industrial facilities benefit from disciplined procurement, measured change control and practical reporting on site progress. Shelta Cost supports clients by translating construction and commercial realities into usable information for decision-making during active delivery.',
            'detail_body_two': 'The firm\'s warehouse and industrial experience strengthens its portfolio across sectors and demonstrates its ability to adapt cost and contract support to more utilitarian, operations-driven project environments.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-6.jpg',
            'checklist': [
                'Industrial cost planning and procurement support',
                'Site progress reporting and delivery visibility',
                'Contract administration for factory and warehouse works',
                'Commercial controls tailored to functionality-driven projects',
            ],
            'sort_order': 6,
            'featured': False,
        },
        {
            'sector': 'Schools and Hostels',
            'title': 'Education, Social Buildings and Hostels',
            'slug': 'education-social-buildings-and-hostels',
            'image': 'assets/img/portfolio/portfolio-4.jpg',
            'client_type': 'Institutional and Social Sector Clients',
            'category': 'Education and Social Facilities',
            'location': 'Kenya',
            'summary': 'Institutional projects including schools, hostels and social buildings requiring practical planning and accountability.',
            'detail_heading': 'Education, Social Buildings and Hostels',
            'detail_intro': 'Shelta Cost has supported education and social-sector assignments including schools, hostels and related institutional buildings. These projects often demand close accountability, efficient use of budget and clear reporting to multiple stakeholders.',
            'detail_body': 'Institutional developments require dependable cost planning and structured contract administration because scope changes and budget sensitivity can have large effects on implementation. The firm helps clients maintain disciplined delivery while keeping project information clear and decision-ready.',
            'detail_body_two': 'This experience complements the commercial, residential and public infrastructure portfolio, showing the firm\'s ability to operate across socially important projects where practical value and cost stewardship matter equally.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-4.jpg',
            'checklist': [
                'Budget-sensitive planning for schools and hostels',
                'Contract and valuation control for institutional works',
                'Stakeholder reporting and delivery visibility',
                'Practical support for socially important building projects',
            ],
            'sort_order': 7,
            'featured': False,
        },
        {
            'sector': 'Public Infrastructure',
            'title': 'Bukhungu Stadium Phase 2',
            'slug': 'bukhungu-stadium-phase-2',
            'image': 'assets/img/portfolio/portfolio-2.jpg',
            'client_type': 'Public Infrastructure',
            'category': 'Sports Facilities and Civil Works',
            'location': 'Kakamega, Kenya',
            'summary': 'A public-sector sports infrastructure assignment that reflects the firm\'s contract, cost and delivery oversight capability.',
            'detail_heading': 'Bukhungu Stadium Phase 2',
            'detail_intro': 'Bukhungu Stadium Phase 2 represents the kind of public-sector assignment where disciplined cost advice, contract administration and delivery oversight matter most. It reflects Shelta Cost Solutions Ltd\'s broader capability in managing complex stakeholder expectations, scope control and project reporting.',
            'detail_body': 'Public infrastructure projects require dependable procurement records, valuation support, progress monitoring and strong reporting to decision-makers. Shelta Cost helps clients maintain visibility on cost movement, delivery status and contractual issues while supporting timely action on emerging risks.',
            'detail_body_two': 'Beyond this case study, the firm\'s wider portfolio includes luxury apartments, bank fit-outs, commercial complexes, industrial facilities and social buildings. Bukhungu Stadium Phase 2 stands out as a strong example of the same disciplined approach applied to civic and sports infrastructure.',
            'gallery_image_left': 'assets/img/about/about-1.jpg',
            'gallery_image_right': 'assets/img/portfolio/portfolio-8.jpg',
            'checklist': [
                'Cost planning, tender documentation and procurement support',
                'Contract administration and payment certification',
                'Programme monitoring and progress reporting',
                'Stakeholder coordination, claims awareness and dispute avoidance',
            ],
            'sort_order': 8,
            'featured': True,
        },
    ]

    for service in services:
        Service.objects.update_or_create(slug=service['slug'], defaults=service)

    for project in projects:
        Project.objects.update_or_create(slug=project['slug'], defaults=project)


def unseed_content(apps, schema_editor):
    Service = apps.get_model('main', 'Service')
    Project = apps.get_model('main', 'Project')
    Service.objects.all().delete()
    Project.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_content, unseed_content),
    ]
