# Generated by Django 5.0.14 on 2026-04-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_update_dgwest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Shelta Cost Company Profile', max_length=200)),
                ('download_url', models.URLField(default='https://example.com/secure/company-profile.pdf', help_text='Temporary secure download URL. Replace later with the Uploadcare-backed file URL.')),
                ('uploadcare_file_id', models.CharField(blank=True, help_text='Optional Uploadcare file UUID or CDN reference.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDownloadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
